<?php require_once __DIR__.'/../config.php'; require_once __DIR__.'/../helpers.php'; require_once __DIR__.'/../i18n.php'; require_auth(['admin']);
$id=(int)($_GET['id']??0); $q=$pdo->prepare('SELECT * FROM questionnaires WHERE id=?'); $q->execute([$id]); $qn=$q->fetch(); if(!$qn){http_response_code(404);echo'Not found';exit;}
if($_SERVER['REQUEST_METHOD']==='POST'&&isset($_POST['add_question'])){$st=$pdo->prepare('INSERT INTO questions (questionnaire_id,item_bank_id,section,text,max_score,weight_percent) VALUES (?,?,?,?,?,?)');$st->execute([$id,$_POST['item_bank_id']?:NULL,$_POST['section']??'',$_POST['text']??'',(int)($_POST['max_score']??5),(int)($_POST['weight_percent']??100)]);redirect('/admin/questionnaire_edit.php?id='.$id);}
if(isset($_GET['delq'])){$qid=(int)$_GET['delq'];$pdo->prepare('DELETE FROM questions WHERE id=?')->execute([$qid]);redirect('/admin/questionnaire_edit.php?id='.$id);}
$itemBanks=$pdo->query('SELECT id,name FROM item_banks ORDER BY name')->fetchAll(); $qs=$pdo->prepare('SELECT * FROM questions WHERE questionnaire_id=? ORDER BY section,id'); $qs->execute([$id]); $questions=$qs->fetchAll();
include __DIR__.'/../templates/header.php'; ?><h2>Edit: <?=h($qn['title'])?></h2>
<form method="post"><input type="hidden" name="add_question" value="1"><div class="row"><label>Item bank</label><select name="item_bank_id"><option value="">(none)</option><?php foreach($itemBanks as $ib):?><option value="<?=$ib['id']?>"><?=h($ib['name'])?></option><?php endforeach; ?></select></div>
<div class="row"><label>Section</label><input name="section"></div><div class="row"><label>Question text</label><textarea name="text" required></textarea></div>
<div class="row"><label>Max score</label><input type="number" name="max_score" value="5" min="1" max="10"></div><div class="row"><label>Weight %</label><input type="number" name="weight_percent" value="100" min="0" max="200"></div><p><button class="btn"><?=h(t('create'))?></button></p></form>
<table><tr><th>Section</th><th>Question</th><th>Max</th><th>Weight%</th><th>Item Bank</th><th></th></tr><?php foreach($questions as $qq):?><tr><td><?=h($qq['section'])?></td><td><?=h($qq['text'])?></td><td><?=$qq['max_score']?></td><td><?=$qq['weight_percent']?></td><td><?=$qq['item_bank_id']?></td><td><a class="btn" href="?id=<?=$id?>&delq=<?=$qq['id']?>" onclick="return confirm('Delete question?')"><?=h(t('delete'))?></a></td></tr><?php endforeach; ?></table>
<?php include __DIR__.'/../templates/footer.php'; ?>
